export const LANGUAGE_CODES = [
    { iso_639_1: "ab", english_name: "Abkhazian", name: "" },
    { iso_639_1: "aa", english_name: "Afar", name: "" },
    { iso_639_1: "af", english_name: "Afrikaans", name: "Afrikaans" },
    { iso_639_1: "ak", english_name: "Akan", name: "" },
    { iso_639_1: "sq", english_name: "Albanian", name: "shqip" },
    { iso_639_1: "am", english_name: "Amharic", name: "" },
    { iso_639_1: "ar", english_name: "Arabic", name: "العربية" },
    { iso_639_1: "an", english_name: "Aragonese", name: "" },
    { iso_639_1: "hy", english_name: "Armenian", name: "" },
    { iso_639_1: "as", english_name: "Assamese", name: "" },
    { iso_639_1: "av", english_name: "Avaric", name: "" },
    { iso_639_1: "ae", english_name: "Avestan", name: "" },
    { iso_639_1: "ay", english_name: "Aymara", name: "" },
    { iso_639_1: "az", english_name: "Azerbaijani", name: "Azərbaycan" },
    { iso_639_1: "bm", english_name: "Bambara", name: "Bamanankan" },
    { iso_639_1: "ba", english_name: "Bashkir", name: "" },
    { iso_639_1: "eu", english_name: "Basque", name: "euskera" },
    { iso_639_1: "be", english_name: "Belarusian", name: "беларуская мова" },
    { iso_639_1: "bn", english_name: "Bengali", name: "বাংলা" },
    { iso_639_1: "bi", english_name: "Bislama", name: "" },
    { iso_639_1: "bs", english_name: "Bosnian", name: "Bosanski" },
    { iso_639_1: "br", english_name: "Breton", name: "" },
    { iso_639_1: "bg", english_name: "Bulgarian", name: "български език" },
    { iso_639_1: "my", english_name: "Burmese", name: "" },
    { iso_639_1: "cn", english_name: "Cantonese", name: "广州话 / 廣州話" },
    { iso_639_1: "ca", english_name: "Catalan", name: "Català" },
    { iso_639_1: "ch", english_name: "Chamorro", name: "Finu' Chamorro" },
    { iso_639_1: "ce", english_name: "Chechen", name: "" },
    { iso_639_1: "ny", english_name: "Chichewa; Nyanja", name: "" },
    { iso_639_1: "cv", english_name: "Chuvash", name: "" },
    { iso_639_1: "kw", english_name: "Cornish", name: "" },
    { iso_639_1: "co", english_name: "Corsican", name: "" },
    { iso_639_1: "cr", english_name: "Cree", name: "" },
    { iso_639_1: "hr", english_name: "Croatian", name: "Hrvatski" },
    { iso_639_1: "cs", english_name: "Czech", name: "Český" },
    { iso_639_1: "da", english_name: "Danish", name: "Dansk" },
    { iso_639_1: "dv", english_name: "Divehi", name: "" },
    { iso_639_1: "nl", english_name: "Dutch", name: "Nederlands" },
    { iso_639_1: "dz", english_name: "Dzongkha", name: "" },
    { iso_639_1: "en", english_name: "English", name: "English" },
    { iso_639_1: "eo", english_name: "Esperanto", name: "Esperanto" },
    { iso_639_1: "et", english_name: "Estonian", name: "Eesti" },
    { iso_639_1: "ee", english_name: "Ewe", name: "Èʋegbe" },
    { iso_639_1: "fo", english_name: "Faroese", name: "" },
    { iso_639_1: "fj", english_name: "Fijian", name: "" },
    { iso_639_1: "fi", english_name: "Finnish", name: "suomi" },
    { iso_639_1: "fr", english_name: "French", name: "Français" },
    { iso_639_1: "fy", english_name: "Frisian", name: "" },
    { iso_639_1: "ff", english_name: "Fulah", name: "Fulfulde" },
    { iso_639_1: "gd", english_name: "Gaelic", name: "" },
    { iso_639_1: "gl", english_name: "Galician", name: "Galego" },
    { iso_639_1: "lg", english_name: "Ganda", name: "" },
    { iso_639_1: "ka", english_name: "Georgian", name: "ქართული" },
    { iso_639_1: "de", english_name: "German", name: "Deutsch" },
    { iso_639_1: "el", english_name: "Greek", name: "ελληνικά" },
    { iso_639_1: "gn", english_name: "Guarani", name: "" },
    { iso_639_1: "gu", english_name: "Gujarati", name: "" },
    { iso_639_1: "ht", english_name: "Haitian; Haitian Creole", name: "" },
    { iso_639_1: "ha", english_name: "Hausa", name: "Hausa" },
    { iso_639_1: "he", english_name: "Hebrew", name: "עִבְרִית" },
    { iso_639_1: "hz", english_name: "Herero", name: "" },
    { iso_639_1: "hi", english_name: "Hindi", name: "हिन्दी" },
    { iso_639_1: "ho", english_name: "Hiri Motu", name: "" },
    { iso_639_1: "hu", english_name: "Hungarian", name: "Magyar" },
    { iso_639_1: "is", english_name: "Icelandic", name: "Íslenska" },
    { iso_639_1: "io", english_name: "Ido", name: "" },
    { iso_639_1: "ig", english_name: "Igbo", name: "" },
    { iso_639_1: "id", english_name: "Indonesian", name: "Bahasa indonesia" },
    { iso_639_1: "ia", english_name: "Interlingua", name: "" },
    { iso_639_1: "ie", english_name: "Interlingue", name: "" },
    { iso_639_1: "iu", english_name: "Inuktitut", name: "" },
    { iso_639_1: "ik", english_name: "Inupiaq", name: "" },
    { iso_639_1: "ga", english_name: "Irish", name: "Gaeilge" },
    { iso_639_1: "it", english_name: "Italian", name: "Italiano" },
    { iso_639_1: "ja", english_name: "Japanese", name: "日本語" },
    { iso_639_1: "jv", english_name: "Javanese", name: "" },
    { iso_639_1: "kl", english_name: "Kalaallisut", name: "" },
    { iso_639_1: "kn", english_name: "Kannada", name: "?????" },
    { iso_639_1: "kr", english_name: "Kanuri", name: "" },
    { iso_639_1: "ks", english_name: "Kashmiri", name: "" },
    { iso_639_1: "kk", english_name: "Kazakh", name: "қазақ" },
    { iso_639_1: "km", english_name: "Khmer", name: "" },
    { iso_639_1: "ki", english_name: "Kikuyu", name: "" },
    { iso_639_1: "rw", english_name: "Kinyarwanda", name: "Kinyarwanda" },
    { iso_639_1: "ky", english_name: "Kirghiz", name: "??????" },
    { iso_639_1: "kv", english_name: "Komi", name: "" },
    { iso_639_1: "kg", english_name: "Kongo", name: "" },
    { iso_639_1: "ko", english_name: "Korean", name: "한국어/조선말" },
    { iso_639_1: "kj", english_name: "Kuanyama", name: "" },
    { iso_639_1: "ku", english_name: "Kurdish", name: "" },
    { iso_639_1: "lo", english_name: "Lao", name: "" },
    { iso_639_1: "la", english_name: "Latin", name: "Latin" },
    { iso_639_1: "lv", english_name: "Latvian", name: "Latviešu" },
    { iso_639_1: "lb", english_name: "Letzeburgesch", name: "" },
    { iso_639_1: "li", english_name: "Limburgish", name: "" },
    { iso_639_1: "ln", english_name: "Lingala", name: "" },
    { iso_639_1: "lt", english_name: "Lithuanian", name: "Lietuvių" },
    { iso_639_1: "lu", english_name: "Luba-Katanga", name: "" },
    { iso_639_1: "mk", english_name: "Macedonian", name: "" },
    { iso_639_1: "mg", english_name: "Malagasy", name: "" },
    { iso_639_1: "ms", english_name: "Malay", name: "Bahasa melayu" },
    { iso_639_1: "ml", english_name: "Malayalam", name: "" },
    { iso_639_1: "mt", english_name: "Maltese", name: "Malti" },
    { iso_639_1: "zh", english_name: "Mandarin", name: "普通话" },
    { iso_639_1: "gv", english_name: "Manx", name: "" },
    { iso_639_1: "mi", english_name: "Maori", name: "" },
    { iso_639_1: "mr", english_name: "Marathi", name: "" },
    { iso_639_1: "mh", english_name: "Marshall", name: "" },
    { iso_639_1: "mo", english_name: "Moldavian", name: "" },
    { iso_639_1: "mn", english_name: "Mongolian", name: "" },
    { iso_639_1: "na", english_name: "Nauru", name: "" },
    { iso_639_1: "nv", english_name: "Navajo", name: "" },
    { iso_639_1: "nd", english_name: "Ndebele", name: "" },
    { iso_639_1: "nr", english_name: "Ndebele", name: "" },
    { iso_639_1: "ng", english_name: "Ndonga", name: "" },
    { iso_639_1: "ne", english_name: "Nepali", name: "" },
    { iso_639_1: "xx", english_name: "No Language", name: "No Language" },
    { iso_639_1: "se", english_name: "Northern Sami", name: "" },
    { iso_639_1: "no", english_name: "Norwegian", name: "Norsk" },
    { iso_639_1: "nb", english_name: "Norwegian Bokmål", name: "Bokmål" },
    { iso_639_1: "nn", english_name: "Norwegian Nynorsk", name: "" },
    { iso_639_1: "oc", english_name: "Occitan", name: "" },
    { iso_639_1: "oj", english_name: "Ojibwa", name: "" },
    { iso_639_1: "or", english_name: "Oriya", name: "" },
    { iso_639_1: "om", english_name: "Oromo", name: "" },
    { iso_639_1: "os", english_name: "Ossetian; Ossetic", name: "" },
    { iso_639_1: "pi", english_name: "Pali", name: "" },
    { iso_639_1: "fa", english_name: "Persian", name: "فارسی" },
    { iso_639_1: "pl", english_name: "Polish", name: "Polski" },
    { iso_639_1: "pt", english_name: "Portuguese", name: "Português" },
    { iso_639_1: "pa", english_name: "Punjabi", name: "ਪੰਜਾਬੀ" },
    { iso_639_1: "ps", english_name: "Pushto", name: "پښتو" },
    { iso_639_1: "qu", english_name: "Quechua", name: "" },
    { iso_639_1: "rm", english_name: "Raeto-Romance", name: "" },
    { iso_639_1: "ro", english_name: "Romanian", name: "Română" },
    { iso_639_1: "rn", english_name: "Rundi", name: "Kirundi" },
    { iso_639_1: "ru", english_name: "Russian", name: "Pусский" },
    { iso_639_1: "sm", english_name: "Samoan", name: "" },
    { iso_639_1: "sg", english_name: "Sango", name: "" },
    { iso_639_1: "sa", english_name: "Sanskrit", name: "" },
    { iso_639_1: "sc", english_name: "Sardinian", name: "" },
    { iso_639_1: "sr", english_name: "Serbian", name: "Srpski" },
    { iso_639_1: "sh", english_name: "Serbo-Croatian", name: "" },
    { iso_639_1: "sn", english_name: "Shona", name: "" },
    { iso_639_1: "sd", english_name: "Sindhi", name: "" },
    { iso_639_1: "si", english_name: "Sinhalese", name: "සිංහල" },
    { iso_639_1: "cu", english_name: "Slavic", name: "" },
    { iso_639_1: "sk", english_name: "Slovak", name: "Slovenčina" },
    { iso_639_1: "sl", english_name: "Slovenian", name: "Slovenščina" },
    { iso_639_1: "so", english_name: "Somali", name: "Somali" },
    { iso_639_1: "st", english_name: "Sotho", name: "" },
    { iso_639_1: "es", english_name: "Spanish", name: "Español" },
    { iso_639_1: "su", english_name: "Sundanese", name: "" },
    { iso_639_1: "sw", english_name: "Swahili", name: "Kiswahili" },
    { iso_639_1: "ss", english_name: "Swati", name: "" },
    { iso_639_1: "sv", english_name: "Swedish", name: "svenska" },
    { iso_639_1: "tl", english_name: "Tagalog", name: "" },
    { iso_639_1: "ty", english_name: "Tahitian", name: "" },
    { iso_639_1: "tg", english_name: "Tajik", name: "" },
    { iso_639_1: "ta", english_name: "Tamil", name: "தமிழ்" },
    { iso_639_1: "tt", english_name: "Tatar", name: "" },
    { iso_639_1: "te", english_name: "Telugu", name: "తెలుగు" },
    { iso_639_1: "th", english_name: "Thai", name: "ภาษาไทย" },
    { iso_639_1: "bo", english_name: "Tibetan", name: "" },
    { iso_639_1: "ti", english_name: "Tigrinya", name: "" },
    { iso_639_1: "to", english_name: "Tonga", name: "" },
    { iso_639_1: "ts", english_name: "Tsonga", name: "" },
    { iso_639_1: "tn", english_name: "Tswana", name: "" },
    { iso_639_1: "tr", english_name: "Turkish", name: "Türkçe" },
    { iso_639_1: "tk", english_name: "Turkmen", name: "" },
    { iso_639_1: "tw", english_name: "Twi", name: "" },
    { iso_639_1: "ug", english_name: "Uighur", name: "" },
    { iso_639_1: "uk", english_name: "Ukrainian", name: "Український" },
    { iso_639_1: "ur", english_name: "Urdu", name: "اردو" },
    { iso_639_1: "uz", english_name: "Uzbek", name: "ozbek" },
    { iso_639_1: "ve", english_name: "Venda", name: "" },
    { iso_639_1: "vi", english_name: "Vietnamese", name: "Tiếng Việt" },
    { iso_639_1: "vo", english_name: "Volapük", name: "" },
    { iso_639_1: "wa", english_name: "Walloon", name: "" },
    { iso_639_1: "cy", english_name: "Welsh", name: "Cymraeg" },
    { iso_639_1: "wo", english_name: "Wolof", name: "Wolof" },
    { iso_639_1: "xh", english_name: "Xhosa", name: "" },
    { iso_639_1: "ii", english_name: "Yi", name: "" },
    { iso_639_1: "yi", english_name: "Yiddish", name: "" },
    { iso_639_1: "yo", english_name: "Yoruba", name: "Èdè Yorùbá" },
    { iso_639_1: "za", english_name: "Zhuang", name: "" },
    { iso_639_1: "zu", english_name: "Zulu", name: "isiZulu" },
];

export const MOVIE_GENRES = [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 14, name: "Fantasy" },
    { id: 36, name: "History" },
    { id: 27, name: "Horror" },
    { id: 10402, name: "Music" },
    { id: 9648, name: "Mystery" },
    { id: 10749, name: "Romance" },
    { id: 878, name: "Science Fiction" },
    { id: 10770, name: "TV Movie" },
    { id: 53, name: "Thriller" },
    { id: 10752, name: "War" },
    { id: 37, name: "Western" },
];

export const TV_GENRES = [
    { id: 10759, name: "Action & Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 10762, name: "Kids" },
    { id: 9648, name: "Mystery" },
    { id: 10763, name: "News" },
    { id: 10764, name: "Reality" },
    { id: 10765, name: "Sci-Fi & Fantasy" },
    { id: 10766, name: "Soap" },
    { id: 10767, name: "Talk" },
    { id: 10768, name: "War & Politics" },
    { id: 37, name: "Western" },
];

export const FILTER_SORT_BY_VALUES = [
    { name: "Popularity Ascending", value: "popularity.asc" },
    { name: "Popularity Descending", value: "popularity.desc" },
    { name: "Release date Ascending", value: "release_date.asc" },
    { name: "Release date Descending", value: "release_date.desc" },
    { name: "Revenue Ascending", value: "revenue.asc" },
    { name: "Revenue Descending", value: "revenue.desc" },
    { name: "Primary release date Ascending", value: "primary_release_date.asc" },
    {
        name: "Primary release date Descending",
        value: "primary_release_date.desc",
    },
    { name: "Title (A-Z)", value: "original_title.asc" },
    { name: "Title (Z-A)", value: "original_title.desc" },
    { name: "Rating Ascending", value: "vote_average.asc" },
    { name: "Rating Descending", value: "vote_average.desc" },
    { name: "Vote count Ascending", value: "vote_count.asc" },
    { name: "Vote count Descending", value: "vote_count.desc" },
];

export const MOVIE_WATCH_PROVIDERS = [
    // {
    //     logo_path: "/9edKQczyuMmQM1yS520hgmJbcaC.jpg",
    //     provider_name: "AMC+ Amazon Channel",
    //     provider_id: 528,
    // },
    // {
    //     logo_path: "/8WWD7t5Irwq9kAH4rufQ4Pe1Dog.jpg",
    //     provider_name: "AcornTV Amazon Channel",
    //     provider_id: 196,
    // },
    // {
    //     logo_path: "/xiqTOBxOnlMy1nvppZcFhCDsP0f.jpg",
    //     provider_name: "Alt Balaji",
    //     provider_id: 319,
    // },
    {
        logo_path: "/emthp39XA2YScoYL1p0sdbAH2WA.jpg",
        provider_name: "Amazon Prime Video",
        provider_id: 119,
    },
    {
        logo_path: "/5NyLm42TmCqCMOZFvH4fcoSNKEW.jpg",
        provider_name: "Amazon Video",
        provider_id: 10,
    },
    {
        logo_path: "/6uhKBfmtzFqOcLousHwZuzcrScK.jpg",
        provider_name: "Apple TV Plus",
        provider_id: 350,
    },
    {
        logo_path: "/peURlLlr8jggOwK53fJ5wdQl05y.jpg",
        provider_name: "Apple iTunes",
        provider_id: 2,
    },
    // {
    //     logo_path: "/xLu1rkZNOKuNnRNr70wySosfTBf.jpg",
    //     provider_name: "BroadwayHD",
    //     provider_id: 554,
    // },
    // {
    //     logo_path: "/iaMw6nOyxUzXSacrLQ0Au6CfZkc.jpg",
    //     provider_name: "Classix",
    //     provider_id: 445,
    // },
    // {
    //     logo_path: "/59azlQKUgFdYq6QI5QEAxIeecyL.jpg",
    //     provider_name: "Cultpix",
    //     provider_id: 692,
    // },
    // {
    //     logo_path: "/67Ee4E6qOkQGHeUTArdJ1qRxzR2.jpg",
    //     provider_name: "Curiosity Stream",
    //     provider_id: 190,
    // },
    // {
    //     logo_path: "/u2H29LCxRzjZVUoZUQAHKm5P8Zc.jpg",
    //     provider_name: "Dekkoo",
    //     provider_id: 444,
    // },
    {
        logo_path: "/wYRiUqIgWcfUvO6OPcXuUNd4tc2.jpg",
        provider_name: "Discovery Plus",
        provider_id: 510,
    },
    // {
    //     logo_path: "/aQ1ritN00jXc7RAFfUoQKGAAfp7.jpg",
    //     provider_name: "DocAlliance Films",
    //     provider_id: 569,
    // },
    // {
    //     logo_path: "/q03pok7xSxYJaENuYs547qa6upY.jpg",
    //     provider_name: "EPIC ON",
    //     provider_id: 476,
    // },
    {
        logo_path: "/4XYI2rzRm34skcvamytegQx7Dmu.jpg",
        provider_name: "Eros Now",
        provider_id: 218,
    },
    // {
    //     logo_path: "/fadQYOyKL0tqfyj012nYJxm3N2I.jpg",
    //     provider_name: "Eventive",
    //     provider_id: 677,
    // },
    // {
    //     logo_path: "/mEiBVz62M9j3TCebmOspMfqkIn.jpg",
    //     provider_name: "FILMRISE",
    //     provider_id: 471,
    // },
    {
        logo_path: "/4FqTBYsUSZgS9z9UGKgxSDBbtc8.jpg",
        provider_name: "FilmBox+",
        provider_id: 701,
    },
    // {
    //     logo_path: "/olmH7t5tEng8Yuq33KmvpvaaVIg.jpg",
    //     provider_name: "Filmzie",
    //     provider_id: 559,
    // },
    {
        logo_path: "/tbEdFQDwx5LEVr8WpSeXQSIirVq.jpg",
        provider_name: "Google Play Movies",
        provider_id: 3,
    },
    // {
    //     logo_path: "/iX0pvJ2GFATbVIH5IHMwG0ffIdV.jpg",
    //     provider_name: "GuideDoc",
    //     provider_id: 100,
    // },
    // {
    //     logo_path: "/d4vHcXY9rwnr763wQns2XJThclt.jpg",
    //     provider_name: "Hoichoi",
    //     provider_id: 315,
    // },
    {
        logo_path: "/7Fl8ylPDclt3ZYgNbW2t7rbZE9I.jpg",
        provider_name: "Hotstar",
        provider_id: 122,
    },
    {
        logo_path: "/4QEQsvCBnORNIg9EDnrRSiEw61D.jpg",
        provider_name: "Hungama Play",
        provider_id: 437,
    },
    {
        logo_path: "/jRpQbuHbGR0MzSIBxJjxZxpXhqC.jpg",
        provider_name: "Jio Cinema",
        provider_id: 220,
    },
    {
        logo_path: "/vrFpju3t7kplDbFsN5GLJpG0obj.jpg",
        provider_name: "Lionsgate Play",
        provider_id: 561,
    },
    {
        logo_path: "/bVR4Z1LCHY7gidXAJF5pMa4QrDS.jpg",
        provider_name: "MUBI",
        provider_id: 11,
    },
    {
        logo_path: "/dH4BZucVyb5lW97TEbZ7RTAugjg.jpg",
        provider_name: "MX Player",
        provider_id: 515,
    },
    // {
    //     logo_path: "/gekkP93StjYdiMAInViVmrnldNY.jpg",
    //     provider_name: "Magellan TV",
    //     provider_id: 551,
    // },
    // {
    //     logo_path: "/iRv3wbUEPuwYYPSKwUxPaMPKGM4.jpg",
    //     provider_name: "ManoramaMax",
    //     provider_id: 482,
    // },
    // {
    //     logo_path: "/fdWE8jpmQqkZrwg2ZMuCLz6ms5P.jpg",
    //     provider_name: "MovieSaints",
    //     provider_id: 562,
    // },
    {
        logo_path: "/t2yyOv40HZeVlLjYsCsPHnWLk4W.jpg",
        provider_name: "Netflix",
        provider_id: 8,
    },
    {
        logo_path: "/j2OLGxyy0gKbPVI0DYFI2hJxP6y.jpg",
        provider_name: "Netflix Kids",
        provider_id: 175,
    },
    {
        logo_path: "/wDWvnupneMbY6RhBTHQC9zU0SCX.jpg",
        provider_name: "Plex",
        provider_id: 538,
    },
    // {
    //     logo_path: "/vIhSFgmp0HXZbUHDscuhpU6S2Z6.jpg",
    //     provider_name: "ShemarooMe",
    //     provider_id: 474,
    // },
    // {
    //     logo_path: "/m0mvKlSjn38S9w7WVNV7a7XyPIe.jpg",
    //     provider_name: "ShortsTV Amazon Channel",
    //     provider_id: 688,
    // },
    {
        logo_path: "/odTur9CmVtzsRUAZ9910tPM4XwL.jpg",
        provider_name: "Sony Liv",
        provider_id: 237,
    },
    // {
    //     logo_path: "/xN97FFkFAdY1JvHhS4zyPD4URgD.jpg",
    //     provider_name: "Spamflix",
    //     provider_id: 521,
    // },
    // {
    //     logo_path: "/iJGVfWTDddgipZ7mJCCEYzmRYrP.jpg",
    //     provider_name: "Spuul",
    //     provider_id: 545,
    // },
    {
        logo_path: "/uW4dPCcbXaaFTyfL5HwhuDt5akK.jpg",
        provider_name: "Sun Nxt",
        provider_id: 309,
    },
    // {
    //     logo_path: "/8ugSQ1g7E8fXFnKFT5G8XOMcmS0.jpg",
    //     provider_name: "TVF Play",
    //     provider_id: 500,
    // },
    // {
    //     logo_path: "/cnIHBy3uLWhHRR7VeWQhK3ZsYP0.jpg",
    //     provider_name: "Takflix",
    //     provider_id: 1771,
    // },
    {
        logo_path: "/qLR6qzB1IcANZUqMEkLf6Sh8Y8s.jpg",
        provider_name: "Tata Play",
        provider_id: 502,
    },
    // {
    //     logo_path: "/osREemsc9uUB2J8VTkQeAVk2fu9.jpg",
    //     provider_name: "True Story",
    //     provider_id: 567,
    // },
    {
        logo_path: "/w2TDH9TRI7pltf5LjN3vXzs7QbN.jpg",
        provider_name: "Tubi TV",
        provider_id: 73,
    },
    {
        logo_path: "/h1PNHFp50cceDZ8jXUMnuVVMIw2.jpg",
        provider_name: "VI movies and tv",
        provider_id: 614,
    },
    {
        logo_path: "/2u1uElmpm4lProS7C9RYcaYLYt1.jpg",
        provider_name: "Voot",
        provider_id: 121,
    },
    {
        logo_path: "/mgD0T960hnYU4gBxbPPBrcDfgWg.jpg",
        provider_name: "WOW Presents Plus",
        provider_id: 546,
    },
    {
        logo_path: "/oIkQkEkwfmcG7IGpRR1NB8frZZM.jpg",
        provider_name: "YouTube",
        provider_id: 192,
    },
    {
        logo_path: "/8qNJcPBHZ4qewHrDJ7C7s2DBQ3V.jpg",
        provider_name: "Yupp TV",
        provider_id: 255,
    },
    {
        logo_path: "/ajbCmwvZ8HiePHZaOVEgm9MzyuA.jpg",
        provider_name: "Zee5",
        provider_id: 232,
    },
    {
        logo_path: "/m3NWxxR23l1w1e156fyTuw931gx.jpg",
        provider_name: "aha",
        provider_id: 532,
    },
];

export const TV_WATCH_PROVIDERS = [
    // {
    //     logo_path: "/9edKQczyuMmQM1yS520hgmJbcaC.jpg",
    //     provider_name: "AMC+ Amazon Channel",
    //     provider_id: 528,
    // },
    // {
    //     logo_path: "/8WWD7t5Irwq9kAH4rufQ4Pe1Dog.jpg",
    //     provider_name: "AcornTV Amazon Channel",
    //     provider_id: 196,
    // },
    // {
    //     logo_path: "/xiqTOBxOnlMy1nvppZcFhCDsP0f.jpg",
    //     provider_name: "Alt Balaji",
    //     provider_id: 319,
    // },
    {
        logo_path: "/emthp39XA2YScoYL1p0sdbAH2WA.jpg",
        provider_name: "Amazon Prime Video",
        provider_id: 119,
    },
    {
        logo_path: "/6uhKBfmtzFqOcLousHwZuzcrScK.jpg",
        provider_name: "Apple TV Plus",
        provider_id: 350,
    },
    // {
    //     logo_path: "/xLu1rkZNOKuNnRNr70wySosfTBf.jpg",
    //     provider_name: "BroadwayHD",
    //     provider_id: 554,
    // },
    // {
    //     logo_path: "/iaMw6nOyxUzXSacrLQ0Au6CfZkc.jpg",
    //     provider_name: "Classix",
    //     provider_id: 445,
    // },
    // {
    //     logo_path: "/8Gt1iClBlzTeQs8WQm8UrCoIxnQ.jpg",
    //     provider_name: "Crunchyroll",
    //     provider_id: 283,
    // },
    // {
    //     logo_path: "/59azlQKUgFdYq6QI5QEAxIeecyL.jpg",
    //     provider_name: "Cultpix",
    //     provider_id: 692,
    // },
    // {
    //     logo_path: "/67Ee4E6qOkQGHeUTArdJ1qRxzR2.jpg",
    //     provider_name: "Curiosity Stream",
    //     provider_id: 190,
    // },
    // {
    //     logo_path: "/u2H29LCxRzjZVUoZUQAHKm5P8Zc.jpg",
    //     provider_name: "Dekkoo",
    //     provider_id: 444,
    // },
    {
        logo_path: "/wYRiUqIgWcfUvO6OPcXuUNd4tc2.jpg",
        provider_name: "Discovery Plus",
        provider_id: 510,
    },
    // {
    //     logo_path: "/q03pok7xSxYJaENuYs547qa6upY.jpg",
    //     provider_name: "EPIC ON",
    //     provider_id: 476,
    // },
    {
        logo_path: "/4XYI2rzRm34skcvamytegQx7Dmu.jpg",
        provider_name: "Eros Now",
        provider_id: 218,
    },
    {
        logo_path: "/mEiBVz62M9j3TCebmOspMfqkIn.jpg",
        provider_name: "FILMRISE",
        provider_id: 471,
    },
    // {
    //     logo_path: "/4FqTBYsUSZgS9z9UGKgxSDBbtc8.jpg",
    //     provider_name: "FilmBox+",
    //     provider_id: 701,
    // },
    // {
    //     logo_path: "/sRMvdhqC7o4BugHKOdgi6IIRRzP.jpg",
    //     provider_name: "Hayu",
    //     provider_id: 223,
    // },
    // {
    //     logo_path: "/d4vHcXY9rwnr763wQns2XJThclt.jpg",
    //     provider_name: "Hoichoi",
    //     provider_id: 315,
    // },
    {
        logo_path: "/7Fl8ylPDclt3ZYgNbW2t7rbZE9I.jpg",
        provider_name: "Hotstar",
        provider_id: 122,
    },
    {
        logo_path: "/4QEQsvCBnORNIg9EDnrRSiEw61D.jpg",
        provider_name: "Hungama Play",
        provider_id: 437,
    },
    {
        logo_path: "/jRpQbuHbGR0MzSIBxJjxZxpXhqC.jpg",
        provider_name: "Jio Cinema",
        provider_id: 220,
    },
    {
        logo_path: "/vrFpju3t7kplDbFsN5GLJpG0obj.jpg",
        provider_name: "Lionsgate Play",
        provider_id: 561,
    },
    {
        logo_path: "/dH4BZucVyb5lW97TEbZ7RTAugjg.jpg",
        provider_name: "MX Player",
        provider_id: 515,
    },
    // {
    //     logo_path: "/gekkP93StjYdiMAInViVmrnldNY.jpg",
    //     provider_name: "Magellan TV",
    //     provider_id: 551,
    // },
    // {
    //     logo_path: "/iRv3wbUEPuwYYPSKwUxPaMPKGM4.jpg",
    //     provider_name: "ManoramaMax",
    //     provider_id: 482,
    // },
    {
        logo_path: "/t2yyOv40HZeVlLjYsCsPHnWLk4W.jpg",
        provider_name: "Netflix",
        provider_id: 8,
    },
    {
        logo_path: "/j2OLGxyy0gKbPVI0DYFI2hJxP6y.jpg",
        provider_name: "Netflix Kids",
        provider_id: 175,
    },
    {
        logo_path: "/wDWvnupneMbY6RhBTHQC9zU0SCX.jpg",
        provider_name: "Plex",
        provider_id: 538,
    },
    // {
    //     logo_path: "/3MflXNopMv3EFKbVgJGoEkJEnnF.jpg",
    //     provider_name: "Rooster Teeth",
    //     provider_id: 485,
    // },
    {
        logo_path: "/odTur9CmVtzsRUAZ9910tPM4XwL.jpg",
        provider_name: "Sony Liv",
        provider_id: 237,
    },
    {
        logo_path: "/uW4dPCcbXaaFTyfL5HwhuDt5akK.jpg",
        provider_name: "Sun Nxt",
        provider_id: 309,
    },
    // {
    //     logo_path: "/8ugSQ1g7E8fXFnKFT5G8XOMcmS0.jpg",
    //     provider_name: "TVF Play",
    //     provider_id: 500,
    // },
    {
        logo_path: "/qLR6qzB1IcANZUqMEkLf6Sh8Y8s.jpg",
        provider_name: "Tata Play",
        provider_id: 502,
    },
    {
        logo_path: "/w2TDH9TRI7pltf5LjN3vXzs7QbN.jpg",
        provider_name: "Tubi TV",
        provider_id: 73,
    },
    {
        logo_path: "/h1PNHFp50cceDZ8jXUMnuVVMIw2.jpg",
        provider_name: "VI movies and tv",
        provider_id: 614,
    },
    {
        logo_path: "/2u1uElmpm4lProS7C9RYcaYLYt1.jpg",
        provider_name: "Voot",
        provider_id: 121,
    },
    // {
    //     logo_path: "/mgD0T960hnYU4gBxbPPBrcDfgWg.jpg",
    //     provider_name: "WOW Presents Plus",
    //     provider_id: 546,
    // },
    {
        logo_path: "/oIkQkEkwfmcG7IGpRR1NB8frZZM.jpg",
        provider_name: "YouTube",
        provider_id: 192,
    },
    {
        logo_path: "/8qNJcPBHZ4qewHrDJ7C7s2DBQ3V.jpg",
        provider_name: "Yupp TV",
        provider_id: 255,
    },
    {
        logo_path: "/ajbCmwvZ8HiePHZaOVEgm9MzyuA.jpg",
        provider_name: "Zee5",
        provider_id: 232,
    },
    {
        logo_path: "/m3NWxxR23l1w1e156fyTuw931gx.jpg",
        provider_name: "aha",
        provider_id: 532,
    },
];

export const REGION_CODES = [
    { name: "Afghanistan", "alpha-2": "AF", "country-code": "004" },
    { name: "Åland Islands", "alpha-2": "AX", "country-code": "248" },
    { name: "Albania", "alpha-2": "AL", "country-code": "008" },
    { name: "Algeria", "alpha-2": "DZ", "country-code": "012" },
    { name: "American Samoa", "alpha-2": "AS", "country-code": "016" },
    { name: "Andorra", "alpha-2": "AD", "country-code": "020" },
    { name: "Angola", "alpha-2": "AO", "country-code": "024" },
    { name: "Anguilla", "alpha-2": "AI", "country-code": "660" },
    { name: "Antarctica", "alpha-2": "AQ", "country-code": "010" },
    { name: "Antigua and Barbuda", "alpha-2": "AG", "country-code": "028" },
    { name: "Argentina", "alpha-2": "AR", "country-code": "032" },
    { name: "Armenia", "alpha-2": "AM", "country-code": "051" },
    { name: "Aruba", "alpha-2": "AW", "country-code": "533" },
    { name: "Australia", "alpha-2": "AU", "country-code": "036" },
    { name: "Austria", "alpha-2": "AT", "country-code": "040" },
    { name: "Azerbaijan", "alpha-2": "AZ", "country-code": "031" },
    { name: "Bahamas", "alpha-2": "BS", "country-code": "044" },
    { name: "Bahrain", "alpha-2": "BH", "country-code": "048" },
    { name: "Bangladesh", "alpha-2": "BD", "country-code": "050" },
    { name: "Barbados", "alpha-2": "BB", "country-code": "052" },
    { name: "Belarus", "alpha-2": "BY", "country-code": "112" },
    { name: "Belgium", "alpha-2": "BE", "country-code": "056" },
    { name: "Belize", "alpha-2": "BZ", "country-code": "084" },
    { name: "Benin", "alpha-2": "BJ", "country-code": "204" },
    { name: "Bermuda", "alpha-2": "BM", "country-code": "060" },
    { name: "Bhutan", "alpha-2": "BT", "country-code": "064" },
    {
        name: "Bolivia (Plurinational State of)",
        "alpha-2": "BO",
        "country-code": "068",
    },
    {
        name: "Bonaire, Sint Eustatius and Saba",
        "alpha-2": "BQ",
        "country-code": "535",
    },
    { name: "Bosnia and Herzegovina", "alpha-2": "BA", "country-code": "070" },
    { name: "Botswana", "alpha-2": "BW", "country-code": "072" },
    { name: "Bouvet Island", "alpha-2": "BV", "country-code": "074" },
    { name: "Brazil", "alpha-2": "BR", "country-code": "076" },
    {
        name: "British Indian Ocean Territory",
        "alpha-2": "IO",
        "country-code": "086",
    },
    { name: "Brunei Darussalam", "alpha-2": "BN", "country-code": "096" },
    { name: "Bulgaria", "alpha-2": "BG", "country-code": "100" },
    { name: "Burkina Faso", "alpha-2": "BF", "country-code": "854" },
    { name: "Burundi", "alpha-2": "BI", "country-code": "108" },
    { name: "Cabo Verde", "alpha-2": "CV", "country-code": "132" },
    { name: "Cambodia", "alpha-2": "KH", "country-code": "116" },
    { name: "Cameroon", "alpha-2": "CM", "country-code": "120" },
    { name: "Canada", "alpha-2": "CA", "country-code": "124" },
    { name: "Cayman Islands", "alpha-2": "KY", "country-code": "136" },
    { name: "Central African Republic", "alpha-2": "CF", "country-code": "140" },
    { name: "Chad", "alpha-2": "TD", "country-code": "148" },
    { name: "Chile", "alpha-2": "CL", "country-code": "152" },
    { name: "China", "alpha-2": "CN", "country-code": "156" },
    { name: "Christmas Island", "alpha-2": "CX", "country-code": "162" },
    { name: "Cocos (Keeling) Islands", "alpha-2": "CC", "country-code": "166" },
    { name: "Colombia", "alpha-2": "CO", "country-code": "170" },
    { name: "Comoros", "alpha-2": "KM", "country-code": "174" },
    { name: "Congo", "alpha-2": "CG", "country-code": "178" },
    {
        name: "Congo, Democratic Republic of the",
        "alpha-2": "CD",
        "country-code": "180",
    },
    { name: "Cook Islands", "alpha-2": "CK", "country-code": "184" },
    { name: "Costa Rica", "alpha-2": "CR", "country-code": "188" },
    { name: "Côte d'Ivoire", "alpha-2": "CI", "country-code": "384" },
    { name: "Croatia", "alpha-2": "HR", "country-code": "191" },
    { name: "Cuba", "alpha-2": "CU", "country-code": "192" },
    { name: "Curaçao", "alpha-2": "CW", "country-code": "531" },
    { name: "Cyprus", "alpha-2": "CY", "country-code": "196" },
    { name: "Czechia", "alpha-2": "CZ", "country-code": "203" },
    { name: "Denmark", "alpha-2": "DK", "country-code": "208" },
    { name: "Djibouti", "alpha-2": "DJ", "country-code": "262" },
    { name: "Dominica", "alpha-2": "DM", "country-code": "212" },
    { name: "Dominican Republic", "alpha-2": "DO", "country-code": "214" },
    { name: "Ecuador", "alpha-2": "EC", "country-code": "218" },
    { name: "Egypt", "alpha-2": "EG", "country-code": "818" },
    { name: "El Salvador", "alpha-2": "SV", "country-code": "222" },
    { name: "Equatorial Guinea", "alpha-2": "GQ", "country-code": "226" },
    { name: "Eritrea", "alpha-2": "ER", "country-code": "232" },
    { name: "Estonia", "alpha-2": "EE", "country-code": "233" },
    { name: "Eswatini", "alpha-2": "SZ", "country-code": "748" },
    { name: "Ethiopia", "alpha-2": "ET", "country-code": "231" },
    {
        name: "Falkland Islands (Malvinas)",
        "alpha-2": "FK",
        "country-code": "238",
    },
    { name: "Faroe Islands", "alpha-2": "FO", "country-code": "234" },
    { name: "Fiji", "alpha-2": "FJ", "country-code": "242" },
    { name: "Finland", "alpha-2": "FI", "country-code": "246" },
    { name: "France", "alpha-2": "FR", "country-code": "250" },
    { name: "French Guiana", "alpha-2": "GF", "country-code": "254" },
    { name: "French Polynesia", "alpha-2": "PF", "country-code": "258" },
    {
        name: "French Southern Territories",
        "alpha-2": "TF",
        "country-code": "260",
    },
    { name: "Gabon", "alpha-2": "GA", "country-code": "266" },
    { name: "Gambia", "alpha-2": "GM", "country-code": "270" },
    { name: "Georgia", "alpha-2": "GE", "country-code": "268" },
    { name: "Germany", "alpha-2": "DE", "country-code": "276" },
    { name: "Ghana", "alpha-2": "GH", "country-code": "288" },
    { name: "Gibraltar", "alpha-2": "GI", "country-code": "292" },
    { name: "Greece", "alpha-2": "GR", "country-code": "300" },
    { name: "Greenland", "alpha-2": "GL", "country-code": "304" },
    { name: "Grenada", "alpha-2": "GD", "country-code": "308" },
    { name: "Guadeloupe", "alpha-2": "GP", "country-code": "312" },
    { name: "Guam", "alpha-2": "GU", "country-code": "316" },
    { name: "Guatemala", "alpha-2": "GT", "country-code": "320" },
    { name: "Guernsey", "alpha-2": "GG", "country-code": "831" },
    { name: "Guinea", "alpha-2": "GN", "country-code": "324" },
    { name: "Guinea-Bissau", "alpha-2": "GW", "country-code": "624" },
    { name: "Guyana", "alpha-2": "GY", "country-code": "328" },
    { name: "Haiti", "alpha-2": "HT", "country-code": "332" },
    {
        name: "Heard Island and McDonald Islands",
        "alpha-2": "HM",
        "country-code": "334",
    },
    { name: "Holy See", "alpha-2": "VA", "country-code": "336" },
    { name: "Honduras", "alpha-2": "HN", "country-code": "340" },
    { name: "Hong Kong", "alpha-2": "HK", "country-code": "344" },
    { name: "Hungary", "alpha-2": "HU", "country-code": "348" },
    { name: "Iceland", "alpha-2": "IS", "country-code": "352" },
    { name: "India", "alpha-2": "IN", "country-code": "356" },
    { name: "Indonesia", "alpha-2": "ID", "country-code": "360" },
    {
        name: "Iran (Islamic Republic of)",
        "alpha-2": "IR",
        "country-code": "364",
    },
    { name: "Iraq", "alpha-2": "IQ", "country-code": "368" },
    { name: "Ireland", "alpha-2": "IE", "country-code": "372" },
    { name: "Isle of Man", "alpha-2": "IM", "country-code": "833" },
    { name: "Israel", "alpha-2": "IL", "country-code": "376" },
    { name: "Italy", "alpha-2": "IT", "country-code": "380" },
    { name: "Jamaica", "alpha-2": "JM", "country-code": "388" },
    { name: "Japan", "alpha-2": "JP", "country-code": "392" },
    { name: "Jersey", "alpha-2": "JE", "country-code": "832" },
    { name: "Jordan", "alpha-2": "JO", "country-code": "400" },
    { name: "Kazakhstan", "alpha-2": "KZ", "country-code": "398" },
    { name: "Kenya", "alpha-2": "KE", "country-code": "404" },
    { name: "Kiribati", "alpha-2": "KI", "country-code": "296" },
    {
        name: "Korea (Democratic People's Republic of)",
        "alpha-2": "KP",
        "country-code": "408",
    },
    { name: "Korea, Republic of", "alpha-2": "KR", "country-code": "410" },
    { name: "Kuwait", "alpha-2": "KW", "country-code": "414" },
    { name: "Kyrgyzstan", "alpha-2": "KG", "country-code": "417" },
    {
        name: "Lao People's Democratic Republic",
        "alpha-2": "LA",
        "country-code": "418",
    },
    { name: "Latvia", "alpha-2": "LV", "country-code": "428" },
    { name: "Lebanon", "alpha-2": "LB", "country-code": "422" },
    { name: "Lesotho", "alpha-2": "LS", "country-code": "426" },
    { name: "Liberia", "alpha-2": "LR", "country-code": "430" },
    { name: "Libya", "alpha-2": "LY", "country-code": "434" },
    { name: "Liechtenstein", "alpha-2": "LI", "country-code": "438" },
    { name: "Lithuania", "alpha-2": "LT", "country-code": "440" },
    { name: "Luxembourg", "alpha-2": "LU", "country-code": "442" },
    { name: "Macao", "alpha-2": "MO", "country-code": "446" },
    { name: "Madagascar", "alpha-2": "MG", "country-code": "450" },
    { name: "Malawi", "alpha-2": "MW", "country-code": "454" },
    { name: "Malaysia", "alpha-2": "MY", "country-code": "458" },
    { name: "Maldives", "alpha-2": "MV", "country-code": "462" },
    { name: "Mali", "alpha-2": "ML", "country-code": "466" },
    { name: "Malta", "alpha-2": "MT", "country-code": "470" },
    { name: "Marshall Islands", "alpha-2": "MH", "country-code": "584" },
    { name: "Martinique", "alpha-2": "MQ", "country-code": "474" },
    { name: "Mauritania", "alpha-2": "MR", "country-code": "478" },
    { name: "Mauritius", "alpha-2": "MU", "country-code": "480" },
    { name: "Mayotte", "alpha-2": "YT", "country-code": "175" },
    { name: "Mexico", "alpha-2": "MX", "country-code": "484" },
    {
        name: "Micronesia (Federated States of)",
        "alpha-2": "FM",
        "country-code": "583",
    },
    { name: "Moldova, Republic of", "alpha-2": "MD", "country-code": "498" },
    { name: "Monaco", "alpha-2": "MC", "country-code": "492" },
    { name: "Mongolia", "alpha-2": "MN", "country-code": "496" },
    { name: "Montenegro", "alpha-2": "ME", "country-code": "499" },
    { name: "Montserrat", "alpha-2": "MS", "country-code": "500" },
    { name: "Morocco", "alpha-2": "MA", "country-code": "504" },
    { name: "Mozambique", "alpha-2": "MZ", "country-code": "508" },
    { name: "Myanmar", "alpha-2": "MM", "country-code": "104" },
    { name: "Namibia", "alpha-2": "NA", "country-code": "516" },
    { name: "Nauru", "alpha-2": "NR", "country-code": "520" },
    { name: "Nepal", "alpha-2": "NP", "country-code": "524" },
    { name: "Netherlands", "alpha-2": "NL", "country-code": "528" },
    { name: "New Caledonia", "alpha-2": "NC", "country-code": "540" },
    { name: "New Zealand", "alpha-2": "NZ", "country-code": "554" },
    { name: "Nicaragua", "alpha-2": "NI", "country-code": "558" },
    { name: "Niger", "alpha-2": "NE", "country-code": "562" },
    { name: "Nigeria", "alpha-2": "NG", "country-code": "566" },
    { name: "Niue", "alpha-2": "NU", "country-code": "570" },
    { name: "Norfolk Island", "alpha-2": "NF", "country-code": "574" },
    { name: "North Macedonia", "alpha-2": "MK", "country-code": "807" },
    { name: "Northern Mariana Islands", "alpha-2": "MP", "country-code": "580" },
    { name: "Norway", "alpha-2": "NO", "country-code": "578" },
    { name: "Oman", "alpha-2": "OM", "country-code": "512" },
    { name: "Pakistan", "alpha-2": "PK", "country-code": "586" },
    { name: "Palau", "alpha-2": "PW", "country-code": "585" },
    { name: "Palestine, State of", "alpha-2": "PS", "country-code": "275" },
    { name: "Panama", "alpha-2": "PA", "country-code": "591" },
    { name: "Papua New Guinea", "alpha-2": "PG", "country-code": "598" },
    { name: "Paraguay", "alpha-2": "PY", "country-code": "600" },
    { name: "Peru", "alpha-2": "PE", "country-code": "604" },
    { name: "Philippines", "alpha-2": "PH", "country-code": "608" },
    { name: "Pitcairn", "alpha-2": "PN", "country-code": "612" },
    { name: "Poland", "alpha-2": "PL", "country-code": "616" },
    { name: "Portugal", "alpha-2": "PT", "country-code": "620" },
    { name: "Puerto Rico", "alpha-2": "PR", "country-code": "630" },
    { name: "Qatar", "alpha-2": "QA", "country-code": "634" },
    { name: "Réunion", "alpha-2": "RE", "country-code": "638" },
    { name: "Romania", "alpha-2": "RO", "country-code": "642" },
    { name: "Russian Federation", "alpha-2": "RU", "country-code": "643" },
    { name: "Rwanda", "alpha-2": "RW", "country-code": "646" },
    { name: "Saint Barthélemy", "alpha-2": "BL", "country-code": "652" },
    {
        name: "Saint Helena, Ascension and Tristan da Cunha",
        "alpha-2": "SH",
        "country-code": "654",
    },
    { name: "Saint Kitts and Nevis", "alpha-2": "KN", "country-code": "659" },
    { name: "Saint Lucia", "alpha-2": "LC", "country-code": "662" },
    {
        name: "Saint Martin (French part)",
        "alpha-2": "MF",
        "country-code": "663",
    },
    { name: "Saint Pierre and Miquelon", "alpha-2": "PM", "country-code": "666" },
    {
        name: "Saint Vincent and the Grenadines",
        "alpha-2": "VC",
        "country-code": "670",
    },
    { name: "Samoa", "alpha-2": "WS", "country-code": "882" },
    { name: "San Marino", "alpha-2": "SM", "country-code": "674" },
    { name: "Sao Tome and Principe", "alpha-2": "ST", "country-code": "678" },
    { name: "Saudi Arabia", "alpha-2": "SA", "country-code": "682" },
    { name: "Senegal", "alpha-2": "SN", "country-code": "686" },
    { name: "Serbia", "alpha-2": "RS", "country-code": "688" },
    { name: "Seychelles", "alpha-2": "SC", "country-code": "690" },
    { name: "Sierra Leone", "alpha-2": "SL", "country-code": "694" },
    { name: "Singapore", "alpha-2": "SG", "country-code": "702" },
    { name: "Sint Maarten (Dutch part)", "alpha-2": "SX", "country-code": "534" },
    { name: "Slovakia", "alpha-2": "SK", "country-code": "703" },
    { name: "Slovenia", "alpha-2": "SI", "country-code": "705" },
    { name: "Solomon Islands", "alpha-2": "SB", "country-code": "090" },
    { name: "Somalia", "alpha-2": "SO", "country-code": "706" },
    { name: "South Africa", "alpha-2": "ZA", "country-code": "710" },
    {
        name: "South Georgia and the South Sandwich Islands",
        "alpha-2": "GS",
        "country-code": "239",
    },
    { name: "South Sudan", "alpha-2": "SS", "country-code": "728" },
    { name: "Spain", "alpha-2": "ES", "country-code": "724" },
    { name: "Sri Lanka", "alpha-2": "LK", "country-code": "144" },
    { name: "Sudan", "alpha-2": "SD", "country-code": "729" },
    { name: "Suriname", "alpha-2": "SR", "country-code": "740" },
    { name: "Svalbard and Jan Mayen", "alpha-2": "SJ", "country-code": "744" },
    { name: "Sweden", "alpha-2": "SE", "country-code": "752" },
    { name: "Switzerland", "alpha-2": "CH", "country-code": "756" },
    { name: "Syrian Arab Republic", "alpha-2": "SY", "country-code": "760" },
    { name: "Taiwan, Province of China", "alpha-2": "TW", "country-code": "158" },
    { name: "Tajikistan", "alpha-2": "TJ", "country-code": "762" },
    {
        name: "Tanzania, United Republic of",
        "alpha-2": "TZ",
        "country-code": "834",
    },
    { name: "Thailand", "alpha-2": "TH", "country-code": "764" },
    { name: "Timor-Leste", "alpha-2": "TL", "country-code": "626" },
    { name: "Togo", "alpha-2": "TG", "country-code": "768" },
    { name: "Tokelau", "alpha-2": "TK", "country-code": "772" },
    { name: "Tonga", "alpha-2": "TO", "country-code": "776" },
    { name: "Trinidad and Tobago", "alpha-2": "TT", "country-code": "780" },
    { name: "Tunisia", "alpha-2": "TN", "country-code": "788" },
    { name: "Turkey", "alpha-2": "TR", "country-code": "792" },
    { name: "Turkmenistan", "alpha-2": "TM", "country-code": "795" },
    { name: "Turks and Caicos Islands", "alpha-2": "TC", "country-code": "796" },
    { name: "Tuvalu", "alpha-2": "TV", "country-code": "798" },
    { name: "Uganda", "alpha-2": "UG", "country-code": "800" },
    { name: "Ukraine", "alpha-2": "UA", "country-code": "804" },
    { name: "United Arab Emirates", "alpha-2": "AE", "country-code": "784" },
    {
        name: "United Kingdom of Great Britain and Northern Ireland",
        "alpha-2": "GB",
        "country-code": "826",
    },
    { name: "United States of America", "alpha-2": "US", "country-code": "840" },
    {
        name: "United States Minor Outlying Islands",
        "alpha-2": "UM",
        "country-code": "581",
    },
    { name: "Uruguay", "alpha-2": "UY", "country-code": "858" },
    { name: "Uzbekistan", "alpha-2": "UZ", "country-code": "860" },
    { name: "Vanuatu", "alpha-2": "VU", "country-code": "548" },
    {
        name: "Venezuela (Bolivarian Republic of)",
        "alpha-2": "VE",
        "country-code": "862",
    },
    { name: "Viet Nam", "alpha-2": "VN", "country-code": "704" },
    { name: "Virgin Islands (British)", "alpha-2": "VG", "country-code": "092" },
    { name: "Virgin Islands (U.S.)", "alpha-2": "VI", "country-code": "850" },
    { name: "Wallis and Futuna", "alpha-2": "WF", "country-code": "876" },
    { name: "Western Sahara", "alpha-2": "EH", "country-code": "732" },
    { name: "Yemen", "alpha-2": "YE", "country-code": "887" },
    { name: "Zambia", "alpha-2": "ZM", "country-code": "894" },
    { name: "Zimbabwe", "alpha-2": "ZW", "country-code": "716" },
];
