export const LANGUAGE_CODES = [
    { iso_639_1: "ab", english_name: "Abkhazian", name: "" },
    { iso_639_1: "aa", english_name: "Afar", name: "" },
    { iso_639_1: "af", english_name: "Afrikaans", name: "Afrikaans" },
    { iso_639_1: "ak", english_name: "Akan", name: "" },
    { iso_639_1: "sq", english_name: "Albanian", name: "shqip" },
    { iso_639_1: "am", english_name: "Amharic", name: "" },
    { iso_639_1: "ar", english_name: "Arabic", name: "العربية" },
    { iso_639_1: "an", english_name: "Aragonese", name: "" },
    { iso_639_1: "hy", english_name: "Armenian", name: "" },
    { iso_639_1: "as", english_name: "Assamese", name: "" },
    { iso_639_1: "av", english_name: "Avaric", name: "" },
    { iso_639_1: "ae", english_name: "Avestan", name: "" },
    { iso_639_1: "ay", english_name: "Aymara", name: "" },
    { iso_639_1: "az", english_name: "Azerbaijani", name: "Azərbaycan" },
    { iso_639_1: "bm", english_name: "Bambara", name: "Bamanankan" },
    { iso_639_1: "ba", english_name: "Bashkir", name: "" },
    { iso_639_1: "eu", english_name: "Basque", name: "euskera" },
    { iso_639_1: "be", english_name: "Belarusian", name: "беларуская мова" },
    { iso_639_1: "bn", english_name: "Bengali", name: "বাংলা" },
    { iso_639_1: "bi", english_name: "Bislama", name: "" },
    { iso_639_1: "bs", english_name: "Bosnian", name: "Bosanski" },
    { iso_639_1: "br", english_name: "Breton", name: "" },
    { iso_639_1: "bg", english_name: "Bulgarian", name: "български език" },
    { iso_639_1: "my", english_name: "Burmese", name: "" },
    { iso_639_1: "cn", english_name: "Cantonese", name: "广州话 / 廣州話" },
    { iso_639_1: "ca", english_name: "Catalan", name: "Català" },
    { iso_639_1: "ch", english_name: "Chamorro", name: "Finu' Chamorro" },
    { iso_639_1: "ce", english_name: "Chechen", name: "" },
    { iso_639_1: "ny", english_name: "Chichewa; Nyanja", name: "" },
    { iso_639_1: "cv", english_name: "Chuvash", name: "" },
    { iso_639_1: "kw", english_name: "Cornish", name: "" },
    { iso_639_1: "co", english_name: "Corsican", name: "" },
    { iso_639_1: "cr", english_name: "Cree", name: "" },
    { iso_639_1: "hr", english_name: "Croatian", name: "Hrvatski" },
    { iso_639_1: "cs", english_name: "Czech", name: "Český" },
    { iso_639_1: "da", english_name: "Danish", name: "Dansk" },
    { iso_639_1: "dv", english_name: "Divehi", name: "" },
    { iso_639_1: "nl", english_name: "Dutch", name: "Nederlands" },
    { iso_639_1: "dz", english_name: "Dzongkha", name: "" },
    { iso_639_1: "en", english_name: "English", name: "English" },
    { iso_639_1: "eo", english_name: "Esperanto", name: "Esperanto" },
    { iso_639_1: "et", english_name: "Estonian", name: "Eesti" },
    { iso_639_1: "ee", english_name: "Ewe", name: "Èʋegbe" },
    { iso_639_1: "fo", english_name: "Faroese", name: "" },
    { iso_639_1: "fj", english_name: "Fijian", name: "" },
    { iso_639_1: "fi", english_name: "Finnish", name: "suomi" },
    { iso_639_1: "fr", english_name: "French", name: "Français" },
    { iso_639_1: "fy", english_name: "Frisian", name: "" },
    { iso_639_1: "ff", english_name: "Fulah", name: "Fulfulde" },
    { iso_639_1: "gd", english_name: "Gaelic", name: "" },
    { iso_639_1: "gl", english_name: "Galician", name: "Galego" },
    { iso_639_1: "lg", english_name: "Ganda", name: "" },
    { iso_639_1: "ka", english_name: "Georgian", name: "ქართული" },
    { iso_639_1: "de", english_name: "German", name: "Deutsch" },
    { iso_639_1: "el", english_name: "Greek", name: "ελληνικά" },
    { iso_639_1: "gn", english_name: "Guarani", name: "" },
    { iso_639_1: "gu", english_name: "Gujarati", name: "" },
    { iso_639_1: "ht", english_name: "Haitian; Haitian Creole", name: "" },
    { iso_639_1: "ha", english_name: "Hausa", name: "Hausa" },
    { iso_639_1: "he", english_name: "Hebrew", name: "עִבְרִית" },
    { iso_639_1: "hz", english_name: "Herero", name: "" },
    { iso_639_1: "hi", english_name: "Hindi", name: "हिन्दी" },
    { iso_639_1: "ho", english_name: "Hiri Motu", name: "" },
    { iso_639_1: "hu", english_name: "Hungarian", name: "Magyar" },
    { iso_639_1: "is", english_name: "Icelandic", name: "Íslenska" },
    { iso_639_1: "io", english_name: "Ido", name: "" },
    { iso_639_1: "ig", english_name: "Igbo", name: "" },
    { iso_639_1: "id", english_name: "Indonesian", name: "Bahasa indonesia" },
    { iso_639_1: "ia", english_name: "Interlingua", name: "" },
    { iso_639_1: "ie", english_name: "Interlingue", name: "" },
    { iso_639_1: "iu", english_name: "Inuktitut", name: "" },
    { iso_639_1: "ik", english_name: "Inupiaq", name: "" },
    { iso_639_1: "ga", english_name: "Irish", name: "Gaeilge" },
    { iso_639_1: "it", english_name: "Italian", name: "Italiano" },
    { iso_639_1: "ja", english_name: "Japanese", name: "日本語" },
    { iso_639_1: "jv", english_name: "Javanese", name: "" },
    { iso_639_1: "kl", english_name: "Kalaallisut", name: "" },
    { iso_639_1: "kn", english_name: "Kannada", name: "?????" },
    { iso_639_1: "kr", english_name: "Kanuri", name: "" },
    { iso_639_1: "ks", english_name: "Kashmiri", name: "" },
    { iso_639_1: "kk", english_name: "Kazakh", name: "қазақ" },
    { iso_639_1: "km", english_name: "Khmer", name: "" },
    { iso_639_1: "ki", english_name: "Kikuyu", name: "" },
    { iso_639_1: "rw", english_name: "Kinyarwanda", name: "Kinyarwanda" },
    { iso_639_1: "ky", english_name: "Kirghiz", name: "??????" },
    { iso_639_1: "kv", english_name: "Komi", name: "" },
    { iso_639_1: "kg", english_name: "Kongo", name: "" },
    { iso_639_1: "ko", english_name: "Korean", name: "한국어/조선말" },
    { iso_639_1: "kj", english_name: "Kuanyama", name: "" },
    { iso_639_1: "ku", english_name: "Kurdish", name: "" },
    { iso_639_1: "lo", english_name: "Lao", name: "" },
    { iso_639_1: "la", english_name: "Latin", name: "Latin" },
    { iso_639_1: "lv", english_name: "Latvian", name: "Latviešu" },
    { iso_639_1: "lb", english_name: "Letzeburgesch", name: "" },
    { iso_639_1: "li", english_name: "Limburgish", name: "" },
    { iso_639_1: "ln", english_name: "Lingala", name: "" },
    { iso_639_1: "lt", english_name: "Lithuanian", name: "Lietuvių" },
    { iso_639_1: "lu", english_name: "Luba-Katanga", name: "" },
    { iso_639_1: "mk", english_name: "Macedonian", name: "" },
    { iso_639_1: "mg", english_name: "Malagasy", name: "" },
    { iso_639_1: "ms", english_name: "Malay", name: "Bahasa melayu" },
    { iso_639_1: "ml", english_name: "Malayalam", name: "" },
    { iso_639_1: "mt", english_name: "Maltese", name: "Malti" },
    { iso_639_1: "zh", english_name: "Mandarin", name: "普通话" },
    { iso_639_1: "gv", english_name: "Manx", name: "" },
    { iso_639_1: "mi", english_name: "Maori", name: "" },
    { iso_639_1: "mr", english_name: "Marathi", name: "" },
    { iso_639_1: "mh", english_name: "Marshall", name: "" },
    { iso_639_1: "mo", english_name: "Moldavian", name: "" },
    { iso_639_1: "mn", english_name: "Mongolian", name: "" },
    { iso_639_1: "na", english_name: "Nauru", name: "" },
    { iso_639_1: "nv", english_name: "Navajo", name: "" },
    { iso_639_1: "nd", english_name: "Ndebele", name: "" },
    { iso_639_1: "nr", english_name: "Ndebele", name: "" },
    { iso_639_1: "ng", english_name: "Ndonga", name: "" },
    { iso_639_1: "ne", english_name: "Nepali", name: "" },
    { iso_639_1: "xx", english_name: "No Language", name: "No Language" },
    { iso_639_1: "se", english_name: "Northern Sami", name: "" },
    { iso_639_1: "no", english_name: "Norwegian", name: "Norsk" },
    { iso_639_1: "nb", english_name: "Norwegian Bokmål", name: "Bokmål" },
    { iso_639_1: "nn", english_name: "Norwegian Nynorsk", name: "" },
    { iso_639_1: "oc", english_name: "Occitan", name: "" },
    { iso_639_1: "oj", english_name: "Ojibwa", name: "" },
    { iso_639_1: "or", english_name: "Oriya", name: "" },
    { iso_639_1: "om", english_name: "Oromo", name: "" },
    { iso_639_1: "os", english_name: "Ossetian; Ossetic", name: "" },
    { iso_639_1: "pi", english_name: "Pali", name: "" },
    { iso_639_1: "fa", english_name: "Persian", name: "فارسی" },
    { iso_639_1: "pl", english_name: "Polish", name: "Polski" },
    { iso_639_1: "pt", english_name: "Portuguese", name: "Português" },
    { iso_639_1: "pa", english_name: "Punjabi", name: "ਪੰਜਾਬੀ" },
    { iso_639_1: "ps", english_name: "Pushto", name: "پښتو" },
    { iso_639_1: "qu", english_name: "Quechua", name: "" },
    { iso_639_1: "rm", english_name: "Raeto-Romance", name: "" },
    { iso_639_1: "ro", english_name: "Romanian", name: "Română" },
    { iso_639_1: "rn", english_name: "Rundi", name: "Kirundi" },
    { iso_639_1: "ru", english_name: "Russian", name: "Pусский" },
    { iso_639_1: "sm", english_name: "Samoan", name: "" },
    { iso_639_1: "sg", english_name: "Sango", name: "" },
    { iso_639_1: "sa", english_name: "Sanskrit", name: "" },
    { iso_639_1: "sc", english_name: "Sardinian", name: "" },
    { iso_639_1: "sr", english_name: "Serbian", name: "Srpski" },
    { iso_639_1: "sh", english_name: "Serbo-Croatian", name: "" },
    { iso_639_1: "sn", english_name: "Shona", name: "" },
    { iso_639_1: "sd", english_name: "Sindhi", name: "" },
    { iso_639_1: "si", english_name: "Sinhalese", name: "සිංහල" },
    { iso_639_1: "cu", english_name: "Slavic", name: "" },
    { iso_639_1: "sk", english_name: "Slovak", name: "Slovenčina" },
    { iso_639_1: "sl", english_name: "Slovenian", name: "Slovenščina" },
    { iso_639_1: "so", english_name: "Somali", name: "Somali" },
    { iso_639_1: "st", english_name: "Sotho", name: "" },
    { iso_639_1: "es", english_name: "Spanish", name: "Español" },
    { iso_639_1: "su", english_name: "Sundanese", name: "" },
    { iso_639_1: "sw", english_name: "Swahili", name: "Kiswahili" },
    { iso_639_1: "ss", english_name: "Swati", name: "" },
    { iso_639_1: "sv", english_name: "Swedish", name: "svenska" },
    { iso_639_1: "tl", english_name: "Tagalog", name: "" },
    { iso_639_1: "ty", english_name: "Tahitian", name: "" },
    { iso_639_1: "tg", english_name: "Tajik", name: "" },
    { iso_639_1: "ta", english_name: "Tamil", name: "தமிழ்" },
    { iso_639_1: "tt", english_name: "Tatar", name: "" },
    { iso_639_1: "te", english_name: "Telugu", name: "తెలుగు" },
    { iso_639_1: "th", english_name: "Thai", name: "ภาษาไทย" },
    { iso_639_1: "bo", english_name: "Tibetan", name: "" },
    { iso_639_1: "ti", english_name: "Tigrinya", name: "" },
    { iso_639_1: "to", english_name: "Tonga", name: "" },
    { iso_639_1: "ts", english_name: "Tsonga", name: "" },
    { iso_639_1: "tn", english_name: "Tswana", name: "" },
    { iso_639_1: "tr", english_name: "Turkish", name: "Türkçe" },
    { iso_639_1: "tk", english_name: "Turkmen", name: "" },
    { iso_639_1: "tw", english_name: "Twi", name: "" },
    { iso_639_1: "ug", english_name: "Uighur", name: "" },
    { iso_639_1: "uk", english_name: "Ukrainian", name: "Український" },
    { iso_639_1: "ur", english_name: "Urdu", name: "اردو" },
    { iso_639_1: "uz", english_name: "Uzbek", name: "ozbek" },
    { iso_639_1: "ve", english_name: "Venda", name: "" },
    { iso_639_1: "vi", english_name: "Vietnamese", name: "Tiếng Việt" },
    { iso_639_1: "vo", english_name: "Volapük", name: "" },
    { iso_639_1: "wa", english_name: "Walloon", name: "" },
    { iso_639_1: "cy", english_name: "Welsh", name: "Cymraeg" },
    { iso_639_1: "wo", english_name: "Wolof", name: "Wolof" },
    { iso_639_1: "xh", english_name: "Xhosa", name: "" },
    { iso_639_1: "ii", english_name: "Yi", name: "" },
    { iso_639_1: "yi", english_name: "Yiddish", name: "" },
    { iso_639_1: "yo", english_name: "Yoruba", name: "Èdè Yorùbá" },
    { iso_639_1: "za", english_name: "Zhuang", name: "" },
    { iso_639_1: "zu", english_name: "Zulu", name: "isiZulu" },
];

export const MOVIE_GENRES = [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 14, name: "Fantasy" },
    { id: 36, name: "History" },
    { id: 27, name: "Horror" },
    { id: 10402, name: "Music" },
    { id: 9648, name: "Mystery" },
    { id: 10749, name: "Romance" },
    { id: 878, name: "Science Fiction" },
    { id: 10770, name: "TV Movie" },
    { id: 53, name: "Thriller" },
    { id: 10752, name: "War" },
    { id: 37, name: "Western" },
];

export const TV_GENRES = [
    { id: 10759, name: "Action & Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 10762, name: "Kids" },
    { id: 9648, name: "Mystery" },
    { id: 10763, name: "News" },
    { id: 10764, name: "Reality" },
    { id: 10765, name: "Sci-Fi & Fantasy" },
    { id: 10766, name: "Soap" },
    { id: 10767, name: "Talk" },
    { id: 10768, name: "War & Politics" },
    { id: 37, name: "Western" },
];

export const FILTER_SORT_BY_VALUES = [
    { name: "Popular ascending", value: "popularity.asc" },
    { name: "Popular descending", value: "popularity.desc" },
    { name: "Release date ascending", value: "release_date.asc" },
    { name: "Release date descending", value: "release_date.desc" },
    { name: "Revenue ascending", value: "revenue.asc" },
    { name: "Revenue descending", value: "revenue.desc" },
    { name: "Primary release date ascending", value: "primary_release_date.asc" },
    {
        name: "Primary release date descending",
        value: "primary_release_date.desc",
    },
    { name: "Original title ascending", value: "original_title.asc" },
    { name: "Original title descending", value: "original_title.desc" },
    { name: "Vote average ascending", value: "vote_average.asc" },
    { name: "Vote average descending", value: "vote_average.desc" },
    { name: "Vote count ascending", value: "vote_count.asc" },
    { name: "Vote count descending", value: "vote_count.desc" },
];

export const MOVIE_WATCH_PROVIDERS = [
    {
        logo_path: "/9edKQczyuMmQM1yS520hgmJbcaC.jpg",
        provider_name: "AMC+ Amazon Channel",
        provider_id: 528,
    },
    {
        logo_path: "/8WWD7t5Irwq9kAH4rufQ4Pe1Dog.jpg",
        provider_name: "AcornTV Amazon Channel",
        provider_id: 196,
    },
    {
        logo_path: "/xiqTOBxOnlMy1nvppZcFhCDsP0f.jpg",
        provider_name: "Alt Balaji",
        provider_id: 319,
    },
    {
        logo_path: "/emthp39XA2YScoYL1p0sdbAH2WA.jpg",
        provider_name: "Amazon Prime Video",
        provider_id: 119,
    },
    {
        logo_path: "/5NyLm42TmCqCMOZFvH4fcoSNKEW.jpg",
        provider_name: "Amazon Video",
        provider_id: 10,
    },
    {
        logo_path: "/6uhKBfmtzFqOcLousHwZuzcrScK.jpg",
        provider_name: "Apple TV Plus",
        provider_id: 350,
    },
    {
        logo_path: "/peURlLlr8jggOwK53fJ5wdQl05y.jpg",
        provider_name: "Apple iTunes",
        provider_id: 2,
    },
    {
        logo_path: "/xLu1rkZNOKuNnRNr70wySosfTBf.jpg",
        provider_name: "BroadwayHD",
        provider_id: 554,
    },
    {
        logo_path: "/iaMw6nOyxUzXSacrLQ0Au6CfZkc.jpg",
        provider_name: "Classix",
        provider_id: 445,
    },
    {
        logo_path: "/59azlQKUgFdYq6QI5QEAxIeecyL.jpg",
        provider_name: "Cultpix",
        provider_id: 692,
    },
    {
        logo_path: "/67Ee4E6qOkQGHeUTArdJ1qRxzR2.jpg",
        provider_name: "Curiosity Stream",
        provider_id: 190,
    },
    {
        logo_path: "/u2H29LCxRzjZVUoZUQAHKm5P8Zc.jpg",
        provider_name: "Dekkoo",
        provider_id: 444,
    },
    {
        logo_path: "/wYRiUqIgWcfUvO6OPcXuUNd4tc2.jpg",
        provider_name: "Discovery Plus",
        provider_id: 510,
    },
    {
        logo_path: "/aQ1ritN00jXc7RAFfUoQKGAAfp7.jpg",
        provider_name: "DocAlliance Films",
        provider_id: 569,
    },
    {
        logo_path: "/q03pok7xSxYJaENuYs547qa6upY.jpg",
        provider_name: "EPIC ON",
        provider_id: 476,
    },
    {
        logo_path: "/4XYI2rzRm34skcvamytegQx7Dmu.jpg",
        provider_name: "Eros Now",
        provider_id: 218,
    },
    {
        logo_path: "/fadQYOyKL0tqfyj012nYJxm3N2I.jpg",
        provider_name: "Eventive",
        provider_id: 677,
    },
    {
        logo_path: "/mEiBVz62M9j3TCebmOspMfqkIn.jpg",
        provider_name: "FILMRISE",
        provider_id: 471,
    },
    {
        logo_path: "/4FqTBYsUSZgS9z9UGKgxSDBbtc8.jpg",
        provider_name: "FilmBox+",
        provider_id: 701,
    },
    {
        logo_path: "/olmH7t5tEng8Yuq33KmvpvaaVIg.jpg",
        provider_name: "Filmzie",
        provider_id: 559,
    },
    {
        logo_path: "/tbEdFQDwx5LEVr8WpSeXQSIirVq.jpg",
        provider_name: "Google Play Movies",
        provider_id: 3,
    },
    {
        logo_path: "/iX0pvJ2GFATbVIH5IHMwG0ffIdV.jpg",
        provider_name: "GuideDoc",
        provider_id: 100,
    },
    {
        logo_path: "/d4vHcXY9rwnr763wQns2XJThclt.jpg",
        provider_name: "Hoichoi",
        provider_id: 315,
    },
    {
        logo_path: "/7Fl8ylPDclt3ZYgNbW2t7rbZE9I.jpg",
        provider_name: "Hotstar",
        provider_id: 122,
    },
    {
        logo_path: "/4QEQsvCBnORNIg9EDnrRSiEw61D.jpg",
        provider_name: "Hungama Play",
        provider_id: 437,
    },
    {
        logo_path: "/jRpQbuHbGR0MzSIBxJjxZxpXhqC.jpg",
        provider_name: "Jio Cinema",
        provider_id: 220,
    },
    {
        logo_path: "/vrFpju3t7kplDbFsN5GLJpG0obj.jpg",
        provider_name: "Lionsgate Play",
        provider_id: 561,
    },
    {
        logo_path: "/bVR4Z1LCHY7gidXAJF5pMa4QrDS.jpg",
        provider_name: "MUBI",
        provider_id: 11,
    },
    {
        logo_path: "/dH4BZucVyb5lW97TEbZ7RTAugjg.jpg",
        provider_name: "MX Player",
        provider_id: 515,
    },
    {
        logo_path: "/gekkP93StjYdiMAInViVmrnldNY.jpg",
        provider_name: "Magellan TV",
        provider_id: 551,
    },
    {
        logo_path: "/iRv3wbUEPuwYYPSKwUxPaMPKGM4.jpg",
        provider_name: "ManoramaMax",
        provider_id: 482,
    },
    {
        logo_path: "/fdWE8jpmQqkZrwg2ZMuCLz6ms5P.jpg",
        provider_name: "MovieSaints",
        provider_id: 562,
    },
    {
        logo_path: "/t2yyOv40HZeVlLjYsCsPHnWLk4W.jpg",
        provider_name: "Netflix",
        provider_id: 8,
    },
    {
        logo_path: "/j2OLGxyy0gKbPVI0DYFI2hJxP6y.jpg",
        provider_name: "Netflix Kids",
        provider_id: 175,
    },
    {
        logo_path: "/wDWvnupneMbY6RhBTHQC9zU0SCX.jpg",
        provider_name: "Plex",
        provider_id: 538,
    },
    {
        logo_path: "/vIhSFgmp0HXZbUHDscuhpU6S2Z6.jpg",
        provider_name: "ShemarooMe",
        provider_id: 474,
    },
    {
        logo_path: "/m0mvKlSjn38S9w7WVNV7a7XyPIe.jpg",
        provider_name: "ShortsTV Amazon Channel",
        provider_id: 688,
    },
    {
        logo_path: "/odTur9CmVtzsRUAZ9910tPM4XwL.jpg",
        provider_name: "Sony Liv",
        provider_id: 237,
    },
    {
        logo_path: "/xN97FFkFAdY1JvHhS4zyPD4URgD.jpg",
        provider_name: "Spamflix",
        provider_id: 521,
    },
    {
        logo_path: "/iJGVfWTDddgipZ7mJCCEYzmRYrP.jpg",
        provider_name: "Spuul",
        provider_id: 545,
    },
    {
        logo_path: "/uW4dPCcbXaaFTyfL5HwhuDt5akK.jpg",
        provider_name: "Sun Nxt",
        provider_id: 309,
    },
    {
        logo_path: "/8ugSQ1g7E8fXFnKFT5G8XOMcmS0.jpg",
        provider_name: "TVF Play",
        provider_id: 500,
    },
    {
        logo_path: "/cnIHBy3uLWhHRR7VeWQhK3ZsYP0.jpg",
        provider_name: "Takflix",
        provider_id: 1771,
    },
    {
        logo_path: "/qLR6qzB1IcANZUqMEkLf6Sh8Y8s.jpg",
        provider_name: "Tata Play",
        provider_id: 502,
    },
    {
        logo_path: "/osREemsc9uUB2J8VTkQeAVk2fu9.jpg",
        provider_name: "True Story",
        provider_id: 567,
    },
    {
        logo_path: "/w2TDH9TRI7pltf5LjN3vXzs7QbN.jpg",
        provider_name: "Tubi TV",
        provider_id: 73,
    },
    {
        logo_path: "/h1PNHFp50cceDZ8jXUMnuVVMIw2.jpg",
        provider_name: "VI movies and tv",
        provider_id: 614,
    },
    {
        logo_path: "/2u1uElmpm4lProS7C9RYcaYLYt1.jpg",
        provider_name: "Voot",
        provider_id: 121,
    },
    {
        logo_path: "/mgD0T960hnYU4gBxbPPBrcDfgWg.jpg",
        provider_name: "WOW Presents Plus",
        provider_id: 546,
    },
    {
        logo_path: "/oIkQkEkwfmcG7IGpRR1NB8frZZM.jpg",
        provider_name: "YouTube",
        provider_id: 192,
    },
    {
        logo_path: "/8qNJcPBHZ4qewHrDJ7C7s2DBQ3V.jpg",
        provider_name: "Yupp TV",
        provider_id: 255,
    },
    {
        logo_path: "/ajbCmwvZ8HiePHZaOVEgm9MzyuA.jpg",
        provider_name: "Zee5",
        provider_id: 232,
    },
    {
        logo_path: "/m3NWxxR23l1w1e156fyTuw931gx.jpg",
        provider_name: "aha",
        provider_id: 532,
    },
];

export const TV_WATCH_PROVIDERS = [
    {
        logo_path: "/9edKQczyuMmQM1yS520hgmJbcaC.jpg",
        provider_name: "AMC+ Amazon Channel",
        provider_id: 528,
    },
    {
        logo_path: "/8WWD7t5Irwq9kAH4rufQ4Pe1Dog.jpg",
        provider_name: "AcornTV Amazon Channel",
        provider_id: 196,
    },
    {
        logo_path: "/xiqTOBxOnlMy1nvppZcFhCDsP0f.jpg",
        provider_name: "Alt Balaji",
        provider_id: 319,
    },
    {
        logo_path: "/emthp39XA2YScoYL1p0sdbAH2WA.jpg",
        provider_name: "Amazon Prime Video",
        provider_id: 119,
    },
    {
        logo_path: "/6uhKBfmtzFqOcLousHwZuzcrScK.jpg",
        provider_name: "Apple TV Plus",
        provider_id: 350,
    },
    {
        logo_path: "/xLu1rkZNOKuNnRNr70wySosfTBf.jpg",
        provider_name: "BroadwayHD",
        provider_id: 554,
    },
    {
        logo_path: "/iaMw6nOyxUzXSacrLQ0Au6CfZkc.jpg",
        provider_name: "Classix",
        provider_id: 445,
    },
    {
        logo_path: "/8Gt1iClBlzTeQs8WQm8UrCoIxnQ.jpg",
        provider_name: "Crunchyroll",
        provider_id: 283,
    },
    {
        logo_path: "/59azlQKUgFdYq6QI5QEAxIeecyL.jpg",
        provider_name: "Cultpix",
        provider_id: 692,
    },
    {
        logo_path: "/67Ee4E6qOkQGHeUTArdJ1qRxzR2.jpg",
        provider_name: "Curiosity Stream",
        provider_id: 190,
    },
    {
        logo_path: "/u2H29LCxRzjZVUoZUQAHKm5P8Zc.jpg",
        provider_name: "Dekkoo",
        provider_id: 444,
    },
    {
        logo_path: "/wYRiUqIgWcfUvO6OPcXuUNd4tc2.jpg",
        provider_name: "Discovery Plus",
        provider_id: 510,
    },
    {
        logo_path: "/q03pok7xSxYJaENuYs547qa6upY.jpg",
        provider_name: "EPIC ON",
        provider_id: 476,
    },
    {
        logo_path: "/4XYI2rzRm34skcvamytegQx7Dmu.jpg",
        provider_name: "Eros Now",
        provider_id: 218,
    },
    {
        logo_path: "/mEiBVz62M9j3TCebmOspMfqkIn.jpg",
        provider_name: "FILMRISE",
        provider_id: 471,
    },
    {
        logo_path: "/4FqTBYsUSZgS9z9UGKgxSDBbtc8.jpg",
        provider_name: "FilmBox+",
        provider_id: 701,
    },
    {
        logo_path: "/sRMvdhqC7o4BugHKOdgi6IIRRzP.jpg",
        provider_name: "Hayu",
        provider_id: 223,
    },
    {
        logo_path: "/d4vHcXY9rwnr763wQns2XJThclt.jpg",
        provider_name: "Hoichoi",
        provider_id: 315,
    },
    {
        logo_path: "/7Fl8ylPDclt3ZYgNbW2t7rbZE9I.jpg",
        provider_name: "Hotstar",
        provider_id: 122,
    },
    {
        logo_path: "/4QEQsvCBnORNIg9EDnrRSiEw61D.jpg",
        provider_name: "Hungama Play",
        provider_id: 437,
    },
    {
        logo_path: "/jRpQbuHbGR0MzSIBxJjxZxpXhqC.jpg",
        provider_name: "Jio Cinema",
        provider_id: 220,
    },
    {
        logo_path: "/vrFpju3t7kplDbFsN5GLJpG0obj.jpg",
        provider_name: "Lionsgate Play",
        provider_id: 561,
    },
    {
        logo_path: "/dH4BZucVyb5lW97TEbZ7RTAugjg.jpg",
        provider_name: "MX Player",
        provider_id: 515,
    },
    {
        logo_path: "/gekkP93StjYdiMAInViVmrnldNY.jpg",
        provider_name: "Magellan TV",
        provider_id: 551,
    },
    {
        logo_path: "/iRv3wbUEPuwYYPSKwUxPaMPKGM4.jpg",
        provider_name: "ManoramaMax",
        provider_id: 482,
    },
    {
        logo_path: "/t2yyOv40HZeVlLjYsCsPHnWLk4W.jpg",
        provider_name: "Netflix",
        provider_id: 8,
    },
    {
        logo_path: "/j2OLGxyy0gKbPVI0DYFI2hJxP6y.jpg",
        provider_name: "Netflix Kids",
        provider_id: 175,
    },
    {
        logo_path: "/wDWvnupneMbY6RhBTHQC9zU0SCX.jpg",
        provider_name: "Plex",
        provider_id: 538,
    },
    {
        logo_path: "/3MflXNopMv3EFKbVgJGoEkJEnnF.jpg",
        provider_name: "Rooster Teeth",
        provider_id: 485,
    },
    {
        logo_path: "/odTur9CmVtzsRUAZ9910tPM4XwL.jpg",
        provider_name: "Sony Liv",
        provider_id: 237,
    },
    {
        logo_path: "/uW4dPCcbXaaFTyfL5HwhuDt5akK.jpg",
        provider_name: "Sun Nxt",
        provider_id: 309,
    },
    {
        logo_path: "/8ugSQ1g7E8fXFnKFT5G8XOMcmS0.jpg",
        provider_name: "TVF Play",
        provider_id: 500,
    },
    {
        logo_path: "/qLR6qzB1IcANZUqMEkLf6Sh8Y8s.jpg",
        provider_name: "Tata Play",
        provider_id: 502,
    },
    {
        logo_path: "/w2TDH9TRI7pltf5LjN3vXzs7QbN.jpg",
        provider_name: "Tubi TV",
        provider_id: 73,
    },
    {
        logo_path: "/h1PNHFp50cceDZ8jXUMnuVVMIw2.jpg",
        provider_name: "VI movies and tv",
        provider_id: 614,
    },
    {
        logo_path: "/2u1uElmpm4lProS7C9RYcaYLYt1.jpg",
        provider_name: "Voot",
        provider_id: 121,
    },
    {
        logo_path: "/mgD0T960hnYU4gBxbPPBrcDfgWg.jpg",
        provider_name: "WOW Presents Plus",
        provider_id: 546,
    },
    {
        logo_path: "/oIkQkEkwfmcG7IGpRR1NB8frZZM.jpg",
        provider_name: "YouTube",
        provider_id: 192,
    },
    {
        logo_path: "/8qNJcPBHZ4qewHrDJ7C7s2DBQ3V.jpg",
        provider_name: "Yupp TV",
        provider_id: 255,
    },
    {
        logo_path: "/ajbCmwvZ8HiePHZaOVEgm9MzyuA.jpg",
        provider_name: "Zee5",
        provider_id: 232,
    },
    {
        logo_path: "/m3NWxxR23l1w1e156fyTuw931gx.jpg",
        provider_name: "aha",
        provider_id: 532,
    },
];
